// <auto-generated />
using System;
using Consult.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cunsult.DataAcess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consult.Models.Departament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departament");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Inxhinieri Kompjuterike dhe Softuerike"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Elektronikë, Automatikë dhe Robotikë"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Teknologjite e Informacionit dhe Komunikimit"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Elektroenergjetike"
                        });
                });

            modelBuilder.Entity("Consult.Models.KonsultimAttend", b =>
                {
                    b.Property<int>("KAid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KAid"));

                    b.Property<bool>("Attending")
                        .HasColumnType("bit");

                    b.Property<int>("Kid")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KAid");

                    b.HasIndex("Kid");

                    b.HasIndex("UserId");

                    b.ToTable("KonsultimAttend");
                });

            modelBuilder.Entity("Consult.Models.Konsultimet", b =>
                {
                    b.Property<int>("Kid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kid"));

                    b.Property<int>("KLid")
                        .HasColumnType("int");

                    b.Property<DateTime>("KkohaEFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KkohaEMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kpershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ktitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Kid");

                    b.HasIndex("KLid");

                    b.HasIndex("UserId");

                    b.ToTable("Konsultimet");
                });

            modelBuilder.Entity("Consult.Models.Lendet", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lid"));

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("VitiID")
                        .HasColumnType("int");

                    b.HasKey("Lid");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("UserId");

                    b.HasIndex("VitiID");

                    b.ToTable("Lendet");

                    b.HasData(
                        new
                        {
                            Lid = 1,
                            DepartamentId = 10,
                            Lname = "Algjebra lineare dhe kalkulus 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 2,
                            DepartamentId = 10,
                            Lname = "Fizika 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 3,
                            DepartamentId = 10,
                            Lname = "Bazat e inxhinierise elektrike 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 4,
                            DepartamentId = 10,
                            Lname = "Bazat e Programimit",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 5,
                            DepartamentId = 10,
                            Lname = "Anglishtja teknike",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 6,
                            DepartamentId = 10,
                            Lname = "Shkathtësi komunikuese",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 7,
                            DepartamentId = 10,
                            Lname = "Gjuhe gjermane",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 8,
                            DepartamentId = 10,
                            Lname = "Praktikum në matematikë",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 9,
                            DepartamentId = 10,
                            Lname = "Kalkulus 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 10,
                            DepartamentId = 10,
                            Lname = "Fizika 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 11,
                            DepartamentId = 10,
                            Lname = "Bazat e inxhinierisë elektrike 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 12,
                            DepartamentId = 10,
                            Lname = "Algoritmet dhe strukturat e të dhënave",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 13,
                            DepartamentId = 10,
                            Lname = "Qarqet digjitale",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 14,
                            DepartamentId = 10,
                            Lname = "Matematika diskrete dhe probabiliteti",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 15,
                            DepartamentId = 10,
                            Lname = "Bazat e të dhënave",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 16,
                            DepartamentId = 10,
                            Lname = "Programimi i orientuar në objekte",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 17,
                            DepartamentId = 10,
                            Lname = "Arkitektura e kompjuterëve",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 18,
                            DepartamentId = 10,
                            Lname = "Elektronika",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 19,
                            DepartamentId = 10,
                            Lname = "Programimi në ueb I",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 20,
                            DepartamentId = 10,
                            Lname = "Sistemet operative",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 21,
                            DepartamentId = 10,
                            Lname = "Inxhinieria softuerike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 22,
                            DepartamentId = 10,
                            Lname = "Siguria e të dhënave",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 23,
                            DepartamentId = 10,
                            Lname = "Komunikimi njeri-kompjuter",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 24,
                            DepartamentId = 10,
                            Lname = "Programimi në ueb II",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 25,
                            DepartamentId = 10,
                            Lname = "Çeshtjet legale, etike dhe sociale ne TIK",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 26,
                            DepartamentId = 10,
                            Lname = "Buxheti dhe analiza e shpenzimeve",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 27,
                            DepartamentId = 10,
                            Lname = "Mikroprocesorët dhe mikrokontrollerët",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 28,
                            DepartamentId = 10,
                            Lname = "Dizajni dhe analiza e algoritmeve",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 29,
                            DepartamentId = 10,
                            Lname = "Rrjetat kompjuterike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 30,
                            DepartamentId = 10,
                            Lname = "Programimi per pajisje mobile",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 31,
                            DepartamentId = 10,
                            Lname = "Inxhinierimi i të dhënave",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 32,
                            DepartamentId = 10,
                            Lname = "Siguria në kompjuter",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 33,
                            DepartamentId = 10,
                            Lname = "Testimi i softuerit",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 34,
                            DepartamentId = 10,
                            Lname = "Concurrent Computing",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 35,
                            DepartamentId = 10,
                            Lname = "Ndërmarresi dhe inovacion",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 36,
                            DepartamentId = 10,
                            Lname = "Menaxhimi i projekteve në TI",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 37,
                            DepartamentId = 10,
                            Lname = "Sistemet e shpërndara",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 38,
                            DepartamentId = 10,
                            Lname = "Gërmimi i të dhënave",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 39,
                            DepartamentId = 10,
                            Lname = "Siguria në internet",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 40,
                            DepartamentId = 10,
                            Lname = "Big data",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 41,
                            DepartamentId = 10,
                            Lname = "Nxjerrja e informatave",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 42,
                            DepartamentId = 10,
                            Lname = "Visual computing",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 43,
                            DepartamentId = 10,
                            Lname = "Cloud computing",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 44,
                            DepartamentId = 10,
                            Lname = "Parallel computing",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 45,
                            DepartamentId = 10,
                            Lname = "Komunikimi i të dhënave",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 46,
                            DepartamentId = 10,
                            Lname = "Biomedical Engineering",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 47,
                            DepartamentId = 10,
                            Lname = "Biometrics & Forensics",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 48,
                            DepartamentId = 10,
                            Lname = "Praktika profesionale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 49,
                            DepartamentId = 10,
                            Lname = "Punimi i diplomës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 50,
                            DepartamentId = 11,
                            Lname = "Algjebra lineare dhe kalkulus 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 51,
                            DepartamentId = 11,
                            Lname = "Fizika 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 52,
                            DepartamentId = 11,
                            Lname = "Bazat e inxhinierisë elektrike 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 53,
                            DepartamentId = 11,
                            Lname = "Bazat e Programimit",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 54,
                            DepartamentId = 11,
                            Lname = "Anglishtja teknike",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 55,
                            DepartamentId = 11,
                            Lname = "Shkathtësi komunikuese",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 56,
                            DepartamentId = 11,
                            Lname = "Gjuhe gjermane",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 57,
                            DepartamentId = 11,
                            Lname = "Praktikum në matematikë",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 58,
                            DepartamentId = 11,
                            Lname = "Kalkulus 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 59,
                            DepartamentId = 11,
                            Lname = "Fizika 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 60,
                            DepartamentId = 11,
                            Lname = "Bazat e inxhinierisë elektrike 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 61,
                            DepartamentId = 11,
                            Lname = "Algoritmet dhe strukturat e të dhënave",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 62,
                            DepartamentId = 11,
                            Lname = "Qarqet digjitale",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 63,
                            DepartamentId = 11,
                            Lname = "Mikroprocesorët dhe mikrokontrollerët",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 64,
                            DepartamentId = 11,
                            Lname = "Kalkulus 3E",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 65,
                            DepartamentId = 11,
                            Lname = "Sinjale dhe sisteme",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 66,
                            DepartamentId = 11,
                            Lname = "Automatika",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 67,
                            DepartamentId = 11,
                            Lname = "Elektronika",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 68,
                            DepartamentId = 11,
                            Lname = "Matjet elektronike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 69,
                            DepartamentId = 11,
                            Lname = "Interneti i gjërave",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 70,
                            DepartamentId = 11,
                            Lname = "Elektroenergjetika",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 71,
                            DepartamentId = 11,
                            Lname = "Fushat dhe valët elektromagnetike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 72,
                            DepartamentId = 11,
                            Lname = "Sinjalet diskrete dhe pёrpunimi digjital",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 73,
                            DepartamentId = 11,
                            Lname = "Arkitektura e kompjuterёve",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 74,
                            DepartamentId = 11,
                            Lname = "Inovacioni dhe biznesi",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 75,
                            DepartamentId = 11,
                            Lname = "Menaxhimi i projekteve",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 76,
                            DepartamentId = 11,
                            Lname = "Komponentët elektronike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 77,
                            DepartamentId = 11,
                            Lname = "Elektronika digjitale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 78,
                            DepartamentId = 11,
                            Lname = "Elektronika energjetike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 79,
                            DepartamentId = 11,
                            Lname = "Optoelektronika",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 80,
                            DepartamentId = 11,
                            Lname = "Sensorët dhe aktuatorët",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 81,
                            DepartamentId = 11,
                            Lname = "Komunikimet elektronike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 82,
                            DepartamentId = 11,
                            Lname = "Instrumentacioni matës dhe DAQ",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 83,
                            DepartamentId = 11,
                            Lname = "Bazat e mekatronikës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 84,
                            DepartamentId = 11,
                            Lname = "Sinjalet biomedicinale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 85,
                            DepartamentId = 11,
                            Lname = "Ndёrmarrёsia",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 86,
                            DepartamentId = 11,
                            Lname = "Mikroekonomia",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 87,
                            DepartamentId = 11,
                            Lname = "Mikroelektronika",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 88,
                            DepartamentId = 11,
                            Lname = "Elektronika analoge",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 89,
                            DepartamentId = 11,
                            Lname = "Bazat e multimedias",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 90,
                            DepartamentId = 11,
                            Lname = "Bazat e robotikës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 91,
                            DepartamentId = 11,
                            Lname = "Teknologjia e komunikimeve optike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 92,
                            DepartamentId = 11,
                            Lname = "Sistemet e ndërthurura ",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 93,
                            DepartamentId = 11,
                            Lname = "Projektimi i sistemeve elektronike me",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 94,
                            DepartamentId = 11,
                            Lname = "Instrumentacioni biomedicinale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 95,
                            DepartamentId = 11,
                            Lname = "Praktika profesionale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 96,
                            DepartamentId = 11,
                            Lname = "Tema e diplomës bachelor",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 97,
                            DepartamentId = 11,
                            Lname = "Sistemet e rregullimit automatik",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 98,
                            DepartamentId = 11,
                            Lname = "Bazat e robotikës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 99,
                            DepartamentId = 11,
                            Lname = "Dirigjuesit e programueshëm logjik ",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 100,
                            DepartamentId = 11,
                            Lname = "Aktuatorët e mençur dhe ngasjet",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 101,
                            DepartamentId = 11,
                            Lname = "Sensorët e mençur",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 102,
                            DepartamentId = 11,
                            Lname = "Komunikimet në automatikë",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 103,
                            DepartamentId = 11,
                            Lname = "Metodat e elementeve tё fundme",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 104,
                            DepartamentId = 11,
                            Lname = "Sistemet operative",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 105,
                            DepartamentId = 11,
                            Lname = "Modelimi dhe simulimi",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 106,
                            DepartamentId = 11,
                            Lname = "Sistemet digjitale tё rregullimit",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 107,
                            DepartamentId = 11,
                            Lname = "Sistemet jolineare të rregullimit",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 108,
                            DepartamentId = 11,
                            Lname = "Rregullimi i proceseve kimike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 109,
                            DepartamentId = 11,
                            Lname = "Proceset e vazhduara dhe grupore",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 110,
                            DepartamentId = 11,
                            Lname = "Rregullimi në kohë reale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 111,
                            DepartamentId = 11,
                            Lname = "Grumbullimi kompjuterik i të dhënave",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 112,
                            DepartamentId = 11,
                            Lname = "Automatizimi i objekteve të banimit",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 113,
                            DepartamentId = 11,
                            Lname = "Praktika profesionale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 114,
                            DepartamentId = 11,
                            Lname = "Tema e diplomës bachelor",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 115,
                            DepartamentId = 12,
                            Lname = "Algjebra lineare dhe kalkulus 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 116,
                            DepartamentId = 12,
                            Lname = "Fizika 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 117,
                            DepartamentId = 12,
                            Lname = "Bazat e inxhinierisë elektrike 1 ",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 118,
                            DepartamentId = 12,
                            Lname = "Bazat e Programimit",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 119,
                            DepartamentId = 12,
                            Lname = "Anglishtja teknike",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 120,
                            DepartamentId = 12,
                            Lname = "Shkathtësi komunikuese",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 121,
                            DepartamentId = 12,
                            Lname = "Gjuhe gjermane",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 122,
                            DepartamentId = 12,
                            Lname = "Praktikum në matematikë",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 123,
                            DepartamentId = 12,
                            Lname = "Kalkulus 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 124,
                            DepartamentId = 12,
                            Lname = "Fizika 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 125,
                            DepartamentId = 12,
                            Lname = "Bazat e inxhinierisë elektrike 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 126,
                            DepartamentId = 12,
                            Lname = "Algoritmet dhe strukturat e të dhënave",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 127,
                            DepartamentId = 12,
                            Lname = "Qarqet digjitale",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 128,
                            DepartamentId = 12,
                            Lname = "Kalkulus 3 dhe probabilitet",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 129,
                            DepartamentId = 12,
                            Lname = "Sinjalet dhe Informacionet",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 130,
                            DepartamentId = 12,
                            Lname = "Elektronikë",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 131,
                            DepartamentId = 12,
                            Lname = "Teknologjitë e Internetit",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 132,
                            DepartamentId = 12,
                            Lname = "Praktikum në Matlab",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 133,
                            DepartamentId = 12,
                            Lname = "Praktikum në Labview",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 134,
                            DepartamentId = 12,
                            Lname = "Komunikimet digjitale",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 135,
                            DepartamentId = 12,
                            Lname = "Valët elektromagnetike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 136,
                            DepartamentId = 12,
                            Lname = "Transmetimi i të dhënave",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 137,
                            DepartamentId = 12,
                            Lname = "Menaxhimi i projekteve ne TIK",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 138,
                            DepartamentId = 12,
                            Lname = "Ekonomia per Inxhinieri",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 139,
                            DepartamentId = 12,
                            Lname = "Arkitektura e kompjutereve dhe pajisjeve",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 140,
                            DepartamentId = 12,
                            Lname = "Zhvillimi i aplikacioneve ne C++",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 141,
                            DepartamentId = 12,
                            Lname = "Zhvillimi i Web aplikacioneve/www",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 142,
                            DepartamentId = 12,
                            Lname = "Rrjetet komunikuese I",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 143,
                            DepartamentId = 12,
                            Lname = "Sistemet operative për TIK",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 144,
                            DepartamentId = 12,
                            Lname = "Programimi i orientuar ne objekte",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 145,
                            DepartamentId = 12,
                            Lname = "Teknologjitë dhe sistemet multimediale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 146,
                            DepartamentId = 12,
                            Lname = "Python",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 147,
                            DepartamentId = 12,
                            Lname = "Zhvillimi aplikacioneve per Android dhe IOS",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 148,
                            DepartamentId = 12,
                            Lname = "Zhvillim i lojerave kompjuterike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 149,
                            DepartamentId = 12,
                            Lname = "Praktikum në Matlab",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 150,
                            DepartamentId = 12,
                            Lname = "Praktikum në Labview",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 151,
                            DepartamentId = 12,
                            Lname = "Inxhinieria e RF dhe Mikrovalëve",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 152,
                            DepartamentId = 12,
                            Lname = "Komunikimet mobile",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 153,
                            DepartamentId = 12,
                            Lname = "Programimi i distribuar",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 154,
                            DepartamentId = 12,
                            Lname = "Rrjetet komunikuese II",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 155,
                            DepartamentId = 12,
                            Lname = "Projekti përfundimtar (Praktika profesionale dhe prezantimi)",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 156,
                            DepartamentId = 12,
                            Lname = "Komunikimet optike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 157,
                            DepartamentId = 12,
                            Lname = "Bioelektromagnetika",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 158,
                            DepartamentId = 12,
                            Lname = "Protokolet komunikuese",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 159,
                            DepartamentId = 12,
                            Lname = "Animimi dhe VR",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 160,
                            DepartamentId = 13,
                            Lname = "Algjebra lineare dhe kalkulus 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 161,
                            DepartamentId = 13,
                            Lname = "Fizika 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 162,
                            DepartamentId = 13,
                            Lname = "Bazat e inxhinierisë elektrike 1",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 163,
                            DepartamentId = 13,
                            Lname = "Bazat e Programimit",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 164,
                            DepartamentId = 13,
                            Lname = "Anglishtja teknike",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 165,
                            DepartamentId = 13,
                            Lname = "Shkathtësi komunikuese",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 166,
                            DepartamentId = 13,
                            Lname = "Gjuhe gjermane",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 167,
                            DepartamentId = 13,
                            Lname = "Praktikum në matematikë",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 168,
                            DepartamentId = 13,
                            Lname = "Kalkulus 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 169,
                            DepartamentId = 13,
                            Lname = "Fizika 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 170,
                            DepartamentId = 13,
                            Lname = "Bazat e inxhinierisë elektrike 2",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 171,
                            DepartamentId = 13,
                            Lname = "Algoritmet dhe strukturat e të dhënave",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 172,
                            DepartamentId = 13,
                            Lname = "Qarqet digjitale",
                            VitiID = 1
                        },
                        new
                        {
                            Lid = 173,
                            DepartamentId = 13,
                            Lname = "Kalkulus 3 dhe probabilitet",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 174,
                            DepartamentId = 13,
                            Lname = "Materialet elektrike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 175,
                            DepartamentId = 13,
                            Lname = "Matjet Elektrike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 176,
                            DepartamentId = 13,
                            Lname = "Bazat e Elektroenergjetikës",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 177,
                            DepartamentId = 13,
                            Lname = "Elektronika",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 178,
                            DepartamentId = 13,
                            Lname = "Bazat e automatikës",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 179,
                            DepartamentId = 13,
                            Lname = "Sinjalet dhe sistemet",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 180,
                            DepartamentId = 13,
                            Lname = "Programimi i orientuar në objekte",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 181,
                            DepartamentId = 13,
                            Lname = "Aplikacionet softwerike në elektroenergjetikë",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 182,
                            DepartamentId = 13,
                            Lname = "Makinat elektrike dhe transformatorët",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 183,
                            DepartamentId = 13,
                            Lname = "Energjia dhe mjedisi",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 184,
                            DepartamentId = 13,
                            Lname = "Centralet elektrike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 185,
                            DepartamentId = 13,
                            Lname = "Fushat dhe valët elektromagnetike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 186,
                            DepartamentId = 13,
                            Lname = "Menaxhimi i energjisë dhe auditimi i efiçiencës",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 187,
                            DepartamentId = 13,
                            Lname = "Instrumentacioni matës në elektroenergjetikë",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 188,
                            DepartamentId = 13,
                            Lname = "Teknika e sigurimit në impiantet elektrike",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 189,
                            DepartamentId = 13,
                            Lname = "Transmetimi i të dhënave",
                            VitiID = 2
                        },
                        new
                        {
                            Lid = 190,
                            DepartamentId = 13,
                            Lname = "Tregu i energjisë elektrike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 191,
                            DepartamentId = 13,
                            Lname = "Bartja dhe shpërndarja e energjisë elektrike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 192,
                            DepartamentId = 13,
                            Lname = "Stabilimentet elektroenergjetike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 193,
                            DepartamentId = 13,
                            Lname = "Instalimet elektrike dhe rrjetat e tensionit",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 194,
                            DepartamentId = 13,
                            Lname = "Burimet e ripërtëritshme të energjisë",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 195,
                            DepartamentId = 13,
                            Lname = "Energjia diellore dhe fotovoltaikët",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 196,
                            DepartamentId = 13,
                            Lname = "Elektronika energjetike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 197,
                            DepartamentId = 13,
                            Lname = "Makinat elektrike speciale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 198,
                            DepartamentId = 13,
                            Lname = "Rrjetat elektrike të fuqisë",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 199,
                            DepartamentId = 13,
                            Lname = "Energjia diellore dhe fotovoltaikët",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 200,
                            DepartamentId = 13,
                            Lname = "Ngasjet elektrike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 201,
                            DepartamentId = 13,
                            Lname = "Mbrojtja e sistemeve elektroenergjetike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 202,
                            DepartamentId = 13,
                            Lname = "Praktika profesionale",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 203,
                            DepartamentId = 13,
                            Lname = "Punimi i Diplomës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 204,
                            DepartamentId = 13,
                            Lname = "Kualiteti i fuqisë në sistemet elektroenergjetike",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 205,
                            DepartamentId = 13,
                            Lname = "Energjia e erës",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 206,
                            DepartamentId = 13,
                            Lname = "Bazat e rrjetave të mençura",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 207,
                            DepartamentId = 13,
                            Lname = "Vlerësimi ekonomik i investimeve",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 208,
                            DepartamentId = 13,
                            Lname = "Menaxhimi i projekteve dhe etika",
                            VitiID = 3
                        },
                        new
                        {
                            Lid = 209,
                            DepartamentId = 13,
                            Lname = "Ndërmarrësia",
                            VitiID = 3
                        });
                });

            modelBuilder.Entity("Consult.Models.Viti", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vid"));

                    b.Property<string>("VitiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vid");

                    b.ToTable("Viti");

                    b.HasData(
                        new
                        {
                            Vid = 1,
                            VitiName = "Viti i parë"
                        },
                        new
                        {
                            Vid = 2,
                            VitiName = "Viti i dytë"
                        },
                        new
                        {
                            Vid = 3,
                            VitiName = "Viti i tretë"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Consult.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartamentID")
                        .HasColumnType("int");

                    b.Property<string>("FKID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VitiID")
                        .HasColumnType("int");

                    b.HasIndex("DepartamentID");

                    b.HasIndex("VitiID");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Consult.Models.KonsultimAttend", b =>
                {
                    b.HasOne("Consult.Models.Konsultimet", "Konsultimet")
                        .WithMany("KonsultimetAttendees")
                        .HasForeignKey("Kid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Consult.Models.ApplicationUser", "User")
                        .WithMany("KonsultimetAttendees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Konsultimet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Consult.Models.Konsultimet", b =>
                {
                    b.HasOne("Consult.Models.Lendet", "Lendet")
                        .WithMany()
                        .HasForeignKey("KLid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consult.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lendet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Consult.Models.Lendet", b =>
                {
                    b.HasOne("Consult.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Consult.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("Consult.Models.Viti", "Viti")
                        .WithMany()
                        .HasForeignKey("VitiID");

                    b.Navigation("Departament");

                    b.Navigation("User");

                    b.Navigation("Viti");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Consult.Models.ApplicationUser", b =>
                {
                    b.HasOne("Consult.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentID");

                    b.HasOne("Consult.Models.Viti", "Viti")
                        .WithMany()
                        .HasForeignKey("VitiID");

                    b.Navigation("Departament");

                    b.Navigation("Viti");
                });

            modelBuilder.Entity("Consult.Models.Konsultimet", b =>
                {
                    b.Navigation("KonsultimetAttendees");
                });

            modelBuilder.Entity("Consult.Models.ApplicationUser", b =>
                {
                    b.Navigation("KonsultimetAttendees");
                });
#pragma warning restore 612, 618
        }
    }
}
