// <auto-generated />
using Consulting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consulting.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Consulting.Models.Lendet", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lid"));

                    b.Property<string>("Ldescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.ToTable("Lendet");

                    b.HasData(
                        new
                        {
                            Lid = 100,
                            Ldescription = "Kjo lende ka 7 kredi",
                            Lname = "Algjebra lineare dhe kalkulus 1"
                        },
                        new
                        {
                            Lid = 101,
                            Ldescription = "Kjo lende ka 6 kredi",
                            Lname = "Fizika 1"
                        },
                        new
                        {
                            Lid = 103,
                            Ldescription = "Kjo lende ka 7 kredi",
                            Lname = "Bazat e inxhinierise elektrike 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
